-- =============================================================
-- AstroHana — DDL completo (estado actual, marzo 2026)
-- Ejecutar en orden si se recrea la instancia desde cero
-- =============================================================

-- ── TABLA PRINCIPAL ───────────────────────────────────────────
CREATE COLUMN TABLE DBADMIN.CARTAS_NATALES (
    ID              INTEGER NOT NULL PRIMARY KEY,
    NOMBRE          NVARCHAR(200),
    LUGAR           NVARCHAR(200),
    ANIO            SMALLINT,
    MES             TINYINT,
    DIA             TINYINT,
    HORA            TINYINT,
    MIN_            TINYINT,
    GMT             DOUBLE,
    LAT             DOUBLE,
    LON             DOUBLE,
    TAGS            NVARCHAR(50),
    DESCRIPCION     NVARCHAR(500),
    -- Posiciones planetarias en grados absolutos 0-360 (pyswisseph, Placidus)
    SOL_GR          DOUBLE,   SOL_SIGNO      TINYINT,  SOL_CASA      TINYINT,
    LUNA_GR         DOUBLE,   LUNA_SIGNO     TINYINT,  LUNA_CASA     TINYINT,
    MERCURIO_GR     DOUBLE,   MERCURIO_SIGNO TINYINT,  MERCURIO_CASA TINYINT,
    VENUS_GR        DOUBLE,   VENUS_SIGNO    TINYINT,  VENUS_CASA    TINYINT,
    MARTE_GR        DOUBLE,   MARTE_SIGNO    TINYINT,  MARTE_CASA    TINYINT,
    JUPITER_GR      DOUBLE,   JUPITER_SIGNO  TINYINT,  JUPITER_CASA  TINYINT,
    SATURNO_GR      DOUBLE,   SATURNO_SIGNO  TINYINT,  SATURNO_CASA  TINYINT,
    URANO_GR        DOUBLE,   URANO_SIGNO    TINYINT,  URANO_CASA    TINYINT,
    NEPTUNO_GR      DOUBLE,   NEPTUNO_SIGNO  TINYINT,  NEPTUNO_CASA  TINYINT,
    PLUTON_GR       DOUBLE,   PLUTON_SIGNO   TINYINT,  PLUTON_CASA   TINYINT,
    ASC_GR          DOUBLE,   ASC_SIGNO      TINYINT,
    MC_GR           DOUBLE,   MC_SIGNO       TINYINT,
    -- Resultados ML (rellenados por kmeans_sklearn.py)
    CLUSTER_ID      INTEGER,
    PC1             DOUBLE,
    PC2             DOUBLE,
    DIST_TO_CENTER  DOUBLE,
    CALC_ERROR      TINYINT DEFAULT 0
);

-- ── TEXTOS INTERPRETATIVOS KEPLER 4 ───────────────────────────
CREATE COLUMN TABLE DBADMIN.KEPLER_TEXTOS (
    ID              INTEGER NOT NULL PRIMARY KEY,
    FICHERO         NVARCHAR(100),   -- PLANETAS.ASC, PAREJA.ASC...
    INDICE          INTEGER,
    CABECERA        NVARCHAR(300),   -- "SOL EN ARIES O CASA 1"
    TEXTO           NCLOB,           -- texto completo interpretativo
    PLANETA1        NVARCHAR(50),
    PLANETA2        NVARCHAR(50),
    SIGNO           NVARCHAR(50),
    CASA            TINYINT,
    ASPECTO         NVARCHAR(50),
    CODIGO_PAREJA   NVARCHAR(50),
    VALENCIA        NVARCHAR(50)
);

-- ── FEATURES PAL (formato long para clustering) ───────────────
-- 8473 cartas × 12 planetas = 101.676 filas
CREATE COLUMN TABLE DBADMIN.PAL_KMEANS_INPUT AS (
    SELECT ID, 'SOL'      AS ATTR_NAME, SOL_GR      AS ATTR_VAL
    FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'LUNA',     LUNA_GR     FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'MERCURIO', MERCURIO_GR FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'VENUS',    VENUS_GR    FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'MARTE',    MARTE_GR    FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'JUPITER',  JUPITER_GR  FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'SATURNO',  SATURNO_GR  FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'URANO',    URANO_GR    FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'NEPTUNO',  NEPTUNO_GR  FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'PLUTON',   PLUTON_GR   FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'ASC',      ASC_GR      FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
    UNION ALL SELECT ID, 'MC',       MC_GR       FROM DBADMIN.CARTAS_NATALES WHERE CALC_ERROR=0
);

-- ── RESULTADOS K-MEANS ─────────────────────────────────────────
CREATE COLUMN TABLE DBADMIN.PAL_KMEANS_RESULT (
    ID INTEGER, CLUSTER_ID INTEGER, DISTANCE DOUBLE);

CREATE COLUMN TABLE DBADMIN.PAL_KMEANS_CENTROIDS (
    CLUSTER_ID INTEGER, ATTR_NAME NVARCHAR(50), CENTROID_VAL DOUBLE);

CREATE COLUMN TABLE DBADMIN.PAL_KM_PARAMS (
    NAME NVARCHAR(256), INTVAL INTEGER, DBLVAL DOUBLE, STRVAL NVARCHAR(1000));
